### ISSUE TITLE
Does not work with npm3 in local installs (was: Performance?)

### ISSUE THREAD

**Issue by djMax** [mscgenjs/mscgenjs-cli#6] opened 2016-01-22 15:59 UTC
I'm wondering if this is normal or I have some other problem. I have a pretty simple MSC file that simply never finishes rendering on Mac OS. None of the CPUs are loaded...

**Comment by djMax** [comment] 2016-01-22 16:01
FYI - it works if installed global rather than local...

**Comment by djMax** [comment] 2016-01-22 19:32
Thanks to @jasisk, we figured out the problem is that npm3 flattens local dependencies. So cli-phantom.html is looking for requirejs in ../node_modules, but that's not where it is anymore, it's in ../.., as are the mscgenjs files. The problem is I'm not sure how you can accomodate both cases easily... Obviously you could just find it on the node side and call different cli-phantom.html's but there's probably a better way.

**Comment by sverweij** [comment] 2016-01-23 16:33
Thanks for reporting (and analyzing) this! 

I'm looking at your pull request right now, and it looks like you found an elegant solution. From the looks of it it might also resolve #5 - which is very likely path related as well.

What platform are you running on?

**Comment by djMax** [comment] 2016-01-23 16:39
I'm on OS X. I can try others if you'd like

**Comment by sverweij** [comment] 2016-01-23 19:21
I'm on OS X (and npm3) too, but couldn't reproduce. Until I realized _dev repo dir structure_ != _installed module repo dir structure_ 

I've merged your PR - I'll publish to npmjs this evening (CET)

**Comment by sverweij** [comment] 2016-01-23 20:26
mscgenjs-cli (@1.3.2) is published to npmjs - and re-retested with node 4/ npm 2 and node 5/ npm 3. 

Thanks again for the PR!

**Closed as completed by sverweij** 2016-01-23 20:26 UTC
Labels: bug

**Comment by djMax** [comment] 2016-01-25 14:31
Thanks for merging and publishing so quickly!
